FROM node:20-alpine

WORKDIR /app
COPY package*.json ./
RUN npm ci --omit=dev --registry=https://registry.npmmirror.com
COPY server ./server

ENV NODE_ENV=production
EXPOSE 8787

CMD ["node", "server/index.js"]
